services:
  - type: web
    name: shambasmart
    env: node
    plan: free
    region: frankfurt
    buildCommand: npm install && npm --prefix frontend/client install && npm --prefix frontend/client run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /api
    autoDeploy: true
